### ISSUE TITLE
don't quantize chroma so coarsely

### ISSUE THREAD

**Issue by metajack** [xiph/daala#55] opened 2015-03-24 01:19 UTC
Thomas Davies found this. Color patches appear where they shouldn't.

**Comment by tmatth** [comment] 2015-06-10 00:17
Duplicate of #8

**Comment by jmvalin** [comment] 2015-11-27 17:11
Should be fixed by David Michael Barr commit 27e3704d919b8b987ecfe513f083cbaf6eaa2d4f

**Closed by jmvalin** 2015-11-27 17:11 UTC
Labels: chroma, duplicate
